Improve readability

diff --git a/bin/start-watchman b/bin/start-watchman
--- a/bin/start-watchman
+++ b/bin/start-watchman
@@ -1,3 +1,8 @@
 #!/bin/bash
-command -v watchman >/dev/null 2>&1 || { echo >&2 "Watchman (https://github.com/facebook/watchman) is not installed. Aborting."; exit 1; }
-watchman-make --pattern 'src/**/*.php' 'tests/**/*.php' 'bin/lean*' --make=composer --target 'test -- --colors=always'
+command -v watchman >/dev/null 2>&1
+if [ $? -ne 0 ]; then
+  echo "Watchman (https://github.com/facebook/watchman) is not installed. Aborting." >&2
+  exit 1;
+fi
+watchman-make --pattern 'src/**/*.php' 'tests/**/*.php' 'bin/lean*' \
+--make=composer --target 'test -- --colors=always'
